### ISSUE TITLE
Ambiguity and alignment does not work. 

### ISSUE THREAD

**Issue by ichem001** [salilab/imp-sampcon#14]
When one tries to compute exhaustiveness of sampling with both flag `--align` and `--ambiguity`, the RMSD calculator does not align and only deals with ambiguity. 

On a small test system with two (2) rigid bodies and seven (7) flexible beads, the sampling precision is computed to be:

- `--align` flag only, the RMSD is 22Å while using 
- `--ambiguity` with and without the `--align` flag, the RMSD is ~12,000Å.

**Comment by ichem001** [comment]
@shruthivis do you have an idea/comment here?

**Comment by shruthivis** [comment]
Most likely I think it is because how we are using symmetry groups in the
RMSD calculator here
https://github.com/salilab/imp-sampcon/blob/8c0533920348f5e06018811b002810d8e3b791cf/pyext/src/rmsd_calculation.py#L351


pyRMSD has a separate fittingCoordset (particles to align over) and
calculationCoordset (particles to calculate RMSD over) in the RMSD
calculators. By default both sets are same (=conforms for us). To use
symmetryGroups, i.e. to specify ambiguity, one needs to explicitly set
fittingCoordsets
and calculationCoordsets.pyRMSD is not aligning the models at all in your
case.

I think the fix is to add `fitSymmetryGroups=symm_groups` as another
argument in line 352 when the RMSD calculator is called? Because we want
ambiguity to be considered while aligning also, not just while calculating
RMSD..

Another reason to get outrageous RMSDs is perhaps your symmetry groups are
not defined correctly. Should be easy to test on your small case. Basically
equivalent copies of a protein should be in the same line of the
symm_groups input text file. I can take a look if you put up a small
example.

**Comment by ichem001** [comment]
@shruthivis Thank you for the detail explanation. As you suspected, the culprit was `calculationCoordsets`. I modified the code for ambiguity and I managed to get both flags to work at the same time. I will push the code after I tested it more. 
I changed:
```
if symm_groups:
    calculator = pyRMSD.RMSDCalculator.RMSDCalculator(
          calculator_name, 
          fittingCoordsets=conforms,
          calculationCoordsets=conforms,
          calcSymmetryGroups=symm_groups)
```
to
```
if symm_groups:
    calculator = pyRMSD.RMSDCalculator.RMSDCalculator(
          calculator_name,
          fittingCoordsets=conforms,
          #calculationCoordsets=conforms,
          calcSymmetryGroups=symm_groups,
          fitSymmetryGroups=symm_groups)
```
The RMSD now are more in line with what I was expecting (~22Å). 

Quick follow-up:
Whether I use ambiguity or not, I get an identical answer from convergence tests; RMSDs, clustering precision, and LPDs are all identical. 
The way I use ambiguity is by importing a text file with the following format:
```
cat ambiguity.txt 
Protein1.0 Protein1.1
```

where `Protein1.0` and `Protein1.1` are the name of the proteins in my topology file.

**Comment by shruthivis** [comment]
Thanks, glad it works.

Did we need to comment out the calculationCoordsets? I thought we needed to
keep it uncommented:   #calculationCoordsets=conforms,
Your ambiguity input seems fine.

We do another RMSD calculation/alignment in precision_rmsd.py to superpose
each model with the cluster centroid to get the densities. I think this fix
is not needed there as we are using QCP_SERIAL_CALCULATOR with the
coordinate sets explicitly defined and symmetry permutations defined
explicitly in the for loop . Can you just crosscheck on your example that
this part is fine?

It is usually the case that the RMSDs are same with and without ambiguity
as the two ambiguous copies usually have distinct conformations in the
models. Only for perfectly symmetric/inter-changeable copies we see
differences in RMSD.

**Comment by ichem001** [comment]
@shruthivis 
May I request your help to solve that issue?
I am writing a test to assess whether the alignment and symmetry groups works as expected. Even with the file showed above, I do not have ambiguity taken into considerations. The reason is the following statement is `False` and therefore no symmetry groups is created by pyRMSD:
https://github.com/salilab/imp-sampcon/blob/f2e734a1f88833b879ea18a5cbf6194c81873387/pyext/src/rmsd_calculation.py#L243

I have print statement everywhere but I am not familiar enough with that part of the code to assess where it goes awry. 
Once we fix this, we will have a test for all combination of RMSD calculator.

I am attaching to this comment:

- two RMFS with two frames each, made up of two proteins, with same sequence, `ProteinA.1` and `ProteinA.3` with the following setup to mimic ambiguity:
- In `SampledA.rmf3`, `ProteinA.1` is an ideal helix and `ProteinA.3` is a string of flexible beads. 
- In `SampledC.rmf3`, `ProteinA.1` is a string of flexible beads and `ProteinA.3` is an ideal helix. 
- the ambiguity file called `ambiguity.txt`.
- a script to compute the RMSD for the following combinations:
- no alignment and no ambiguity
- alignment and no ambiguity
- alignment and ambiguity

To run the code, 
`$PATH_TO_IMP_ENV python test_ambiguous_rmsd.py`


The expectation is that every time we add a layer, RMSD should decrease because in that setup the rotation of 180º should give a better fit. 

Also - remember to change the code at line L283 to:
```
print("We are dealing with ambiguity, ", symm_groups)
        calculator = pyRMSD.RMSDCalculator.RMSDCalculator(
            calculator_name,
            fittingCoordsets=conforms,
            #calculationCoordsets=conforms,                                                       
            calcSymmetryGroups=symm_groups,
            fitSymmetryGroups=symm_groups)
```

[test_ambiguity.zip](https://github.com/salilab/imp-sampcon/files/6354921/test_ambiguity.zip)

**Comment by ichem001** [comment]
@BIORAK found out an issue with my `ambiguity` format file. 
The ambiguity now is being read and I see the correct pair of ambiguous beads being tested. As @shruthivis mentioned, the `rmsd` with and without alignment for two ambiguous copies because both copies have distinct conformations in the models. Only for perfectly symmetric/inter-changeable copies we see differences in RMSD.

**Comment by benmwebb** [comment]
@ichem001 wouldn't it make sense for the code to throw an error if given a broken ambiguity file rather than silently just not working? What was the nature of the issue with your file?

**Comment by ichem001** [comment]
> @ichem001 wouldn't it make sense for the code to throw an error if given a broken ambiguity file rather than silently just not working? What was the nature of the issue with your file?
Agreed - still not convinced that the code as expected though. Have not been able to write **a good unit test**. 

the error I had had to do with how I generated the hierarchy. 
Instead of using `create_copy()` I did:
```
# Protein A.3
m1A = st1.create_molecule('ProteinA.3', sequence, chain_id='A')
m1A.add_representation(m1A, [1], ideal_helix=True)
# Protein A.1
m1B = st1.create_molecule('ProteinA.1', sequence, chain_id='B')
m1B.add_representation(m1B, [1])
```

And my ambiguity file needed to have the copy number in this case `ProteinA.1.0` and `ProteinA.3.0`. 
I assumed that `.1` and `.3` would have been understood as copy number.

**Comment by shruthivis** [comment]
@ichem001 back to this, sorry for the delay. Checked the code and I think
the issue is sorted now. You could push the new code to github and it would
be great if you could include this test in the sampcon test suite. If you
send the new RMF input files (the one with the correct way to create
ambiguous proteins) I could create this test too.

@benmwebb The imp-sampcon input for ambiguity simply has lines like
A.0 A.1

if copies 0 and 1 are symmetrical for protein A. In the rmsd_calculation
code these protein copy names in the ambiguity file are matched against the
hierarchy by getting the protein name and copy number from the hierarchy
here
https://github.com/salilab/imp-sampcon/blob/f2e734a1f88833b879ea18a5cbf6194c81873387/pyext/src/rmsd_calculation.py#L234-L241


In Ilan's case the protein_plus_copy from the hierarchy (ProteinA.3.0)
didnt match the line in the ambiguity file (ProteinA.3) and it simply
created no symmetry groups since the if statement here
https://github.com/salilab/imp-sampcon/blob/f2e734a1f88833b879ea18a5cbf6194c81873387/pyext/src/rmsd_calculation.py#L243
was false.

The best place to flag an error is probably at the end of
`get_rmfs_coordinates_one_rmf`: halt with error message if ambiguity option
is set and `symm_groups` is empty after `get_rmfs_coordinates_one_rmf`
finishes.

**Comment by ichem001** [comment]
@shruthivis -- I think with the warning that @benmwebb added to `pmi` (see commit #256 in `pmi`) and the latest push in this repo, maybe we can close that issue. What do you think?

**Comment by shruthivis** [comment]
Yes, fine with me. I will add the extra error check I mentioned to a PR I
am creating.
